Repository eloqdata/eloqdoc, pull requests merged in 2025-08, with the labels that each got.

#59 CI integrate tpcc
  concourse/pipeline/main.ent.yml
  concourse/pipeline/main.yml
  concourse/pipeline/pr.ent.yml
  concourse/scripts/common.sh
  concourse/scripts/main.bash
  concourse/scripts/main.ent.bash
  concourse/scripts/mongod.conf
  concourse/scripts/nightly_build.ent.bash
  concourse/scripts/pr.ent.bash
  concourse/scripts/pytpcc.cfg
  concourse/scripts/store_rocksdb_cloud.yaml
Labels: trigger-ci

#60 switch to run CI with eloqdata docker images
  concourse/pipeline/main.ent.yml
  concourse/pipeline/main.yml
  concourse/pipeline/nightly_build.ent.yml
  concourse/pipeline/pr.ent.yml
  concourse/scripts/common.sh
  concourse/scripts/main.bash
  concourse/scripts/main.ent.bash
  concourse/scripts/mongod.conf
  concourse/scripts/pr.ent.bash
  concourse/scripts/store_rocksdb_cloud.yaml
  config/example.conf
Labels: test

#84 Fix namespace exists error
  src/mongo/db/modules/eloq/src/eloq_record_store.cpp
  src/mongo/db/modules/eloq/src/eloq_record_store.h
  src/mongo/db/ops/write_ops_exec.cpp
Labels: trigger-ci

#105 Add options for txlog rocksdb cloud
  concourse/scripts/common.sh
  concourse/scripts/mongod.conf
  concourse/scripts/store_rocksdb_cloud.yaml
  config/store_rocksdb_cloud.yaml
  src/mongo/db/modules/eloq/src/eloq_global_options.cpp
  src/mongo/db/modules/eloq/src/eloq_global_options.h
  src/mongo/db/modules/eloq/src/eloq_kv_engine.cpp
Labels: enhancement
